select distinct idea, subject, verb, object 
from labels
where idea not like '%accepted%'
and  idea not like '%rejected%'
and  idea not like '%proposal%'
and  idea not like '%deferred%'
and  idea not like '%postponed%'
and  idea not like '%incomplete%'
and  idea not like '%final%'
and  idea not like '%draft%'
and  idea not like '%active%'
and  idea not like '%finished%'
and  idea not like '%discussion%'
and  idea not like '%replaced%'
and  idea not like '%pending%'
and  idea not like '%closed%'
and  idea not like '%open%'
and  idea not like '%complete%'
and  idea not like '%updated%'