-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.25 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5151
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table peps_bck.pepdetails
DROP TABLE IF EXISTS `pepdetails`;
CREATE TABLE IF NOT EXISTS `pepdetails` (
  `pep` int(11) DEFAULT NULL,
  `title` text,
  `author` text,
  `type` text,
  `bdfl_delegate` text,
  `created` date DEFAULT NULL,
  `pepSummary` text,
  `python_version` text,
  KEY `pep_index` (`pep`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table peps_bck.pepdetails: ~420 rows (approximately)
/*!40000 ALTER TABLE `pepdetails` DISABLE KEYS */;
INSERT INTO `pepdetails` (`pep`, `title`, `author`, `type`, `bdfl_delegate`, `created`, `pepSummary`, `python_version`) VALUES
	(1, ' PEP Purpose and Guidelines', ' Barry Warsaw, Jeremy Hylton, David Goodger, Nick Coghlan', ' Process', NULL, NULL, NULL, NULL),
	(2, ' Procedure for Adding New Modules', ' Martijn Faassen &lt;faassen@infrae.com&gt;', ' Process', NULL, NULL, NULL, NULL),
	(3, ' Guidelines for Handling Bug Reports', ' jeremy@alum.mit.edu (Jeremy Hylton)', ' Process', NULL, NULL, NULL, NULL),
	(4, ' Deprecation of Standard Modules', ' Brett Cannon &lt;brett@python.org&gt;, Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Process', NULL, NULL, NULL, NULL),
	(5, ' Guidelines for Language Evolution', ' paul@prescod.net (Paul Prescod)', ' Process', NULL, NULL, NULL, NULL),
	(6, ' Bug Fix Releases', ' aahz@pythoncraft.com (Aahz), anthony@interlink.com.au (Anthony Baxter)', ' Process', NULL, NULL, NULL, NULL),
	(7, ' Style Guide for C Code', ' Guido van Rossum &lt;guido@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(8, ' Style Guide for Python Code', ' Guido van Rossum &lt;guido@python.org&gt;,', ' Process', NULL, NULL, NULL, NULL),
	(9, ' Sample Plaintext PEP Template', ' Barry Warsaw &lt;barry@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(10, ' Voting Guidelines', ' barry@python.org (Barry Warsaw)', ' Process', NULL, NULL, NULL, NULL),
	(11, ' Removing support for little used platforms', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;,', ' Process', NULL, NULL, NULL, NULL),
	(12, ' Sample reStructuredText PEP Template', ' David Goodger &lt;goodger@python.org&gt;,', ' Process', NULL, NULL, NULL, NULL),
	(20, ' The Zen of Python', ' tim.peters@gmail.com (Tim Peters)', ' Informational', NULL, NULL, NULL, NULL),
	(42, ' Feature Requests', ' Jeremy Hylton &lt;jeremy@alum.mit.edu&gt;', ' Process', NULL, NULL, NULL, NULL),
	(100, ' Python Unicode Integration', ' mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(101, ' Doing Python Releases 101', ' barry@python.org (Barry Warsaw), guido@python.org (Guido van Rossum)', ' Informational', NULL, NULL, NULL, NULL),
	(102, ' Doing Python Micro Releases', ' anthony@interlink.com.au (Anthony Baxter), ', ' Informational', NULL, NULL, NULL, NULL),
	(103, ' Collecting information about git', ' Oleg Broytman &lt;phd@phdru.name&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(160, ' Python 1.6 Release Schedule', ' Fred L. Drake, Jr. &lt;fdrake@acm.org&gt;', ' Informational', NULL, NULL, NULL, ' 1.6'),
	(200, ' Python 2.0 Release Schedule', ' Jeremy Hylton &lt;jeremy@alum.mit.edu&gt;', ' Informational', NULL, NULL, NULL, ' 2.0'),
	(201, ' Lockstep Iteration', ' barry@python.org (Barry Warsaw)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(202, ' List Comprehensions', ' barry@python.org (Barry Warsaw)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(203, ' Augmented Assignments', ' thomas@python.org (Thomas Wouters)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(204, ' Range Literals', ' thomas@python.org (Thomas Wouters)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(205, ' Weak References', ' Fred L. Drake, Jr. &lt;fdrake@acm.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(206, ' Python Advanced Library', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(207, ' Rich Comparisons', ' guido@python.org (Guido van Rossum), DavidA@ActiveState.com (David Ascher)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(208, ' Reworking the Coercion Model', ' nas@arctrix.com (Neil Schemenauer), mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(209, ' Multi-dimensional Arrays', ' barrett@stsci.edu (Paul Barrett), oliphant@ee.byu.edu (Travis Oliphant)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(210, ' Decoupling the Interpreter Loop', ' davida@activestate.com (David Ascher)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(211, ' Adding A New Outer Product Operator', ' gvwilson@ddj.com (Greg Wilson)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(212, ' Loop Counter Iteration', ' nowonder@nowonder.de (Peter Schneider-Kamp)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(213, ' Attribute Access Handlers', ' paul@prescod.net (Paul Prescod)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(214, ' Extended Print Statement', ' barry@python.org (Barry Warsaw)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(215, ' String Interpolation', ' ping@zesty.ca (Ka-Ping Yee)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(216, ' Docstring Format', ' moshez@zadka.site.co.il (Moshe Zadka)', ' Informational', NULL, NULL, NULL, NULL),
	(217, ' Display Hook for Interactive Use', ' moshez@zadka.site.co.il (Moshe Zadka)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(218, ' Adding a Built-In Set Object Type', ' gvwilson@ddj.com (Greg Wilson), python@rcn.com (Raymond Hettinger)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(219, ' Stackless Python', ' gmcm@hypernet.com (Gordon McMillan)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(220, ' Coroutines, Generators, Continuations', ' gmcm@hypernet.com (Gordon McMillan)', ' Informational', NULL, NULL, NULL, NULL),
	(221, ' Import As', ' thomas@python.org (Thomas Wouters)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(222, ' Web Library Enhancements', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(223, ' Change the Meaning of ``\\x`` Escapes', ' tim.peters@gmail.com (Tim Peters)', ' Standards Track', NULL, NULL, NULL, ' 2.0'),
	(224, ' Attribute Docstrings', ' mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(225, ' Elementwise/Objectwise Operators', ' hzhu@users.sourceforge.net (Huaiyu Zhu),', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(226, ' Python 2.1 Release Schedule', ' Jeremy Hylton &lt;jeremy@alum.mit.edu&gt;', ' Informational', NULL, NULL, NULL, ' 2.1'),
	(227, ' Statically Nested Scopes', ' jeremy@alum.mit.edu (Jeremy Hylton)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(228, ' Reworking Python&#39;s Numeric Model', ' moshez@zadka.site.co.il (Moshe Zadka), guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, NULL),
	(229, ' Using Distutils to Build Python', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(230, ' Warning Framework', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(231, ' __findattr__()', ' barry@python.org (Barry Warsaw)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(232, ' Function Attributes', ' Barry Warsaw &lt;barry@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(233, ' Python Online Help', ' paul@prescod.net (Paul Prescod)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(234, ' Iterators', ' ping@zesty.ca (Ka-Ping Yee), guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(235, ' Import on Case-Insensitive Platforms', ' Tim Peters &lt;tim.peters@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(236, ' Back to the __future__', ' Tim Peters &lt;tim.peters@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(237, ' Unifying Long Integers and Integers', ' Moshe Zadka, Guido van Rossum', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(238, ' Changing the Division Operator', ' moshez@zadka.site.co.il (Moshe Zadka), guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(239, ' Adding a Rational Type to Python', ' Christopher A. Craig &lt;python-pep@ccraig.org&gt;, Moshe Zadka &lt;moshez@zadka.site.co.il&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(240, ' Adding a Rational Literal to Python', ' Christopher A. Craig &lt;python-pep@ccraig.org&gt;, Moshe Zadka &lt;moshez@zadka.site.co.il&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(241, ' Metadata for Python Software Packages', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(242, ' Numeric Kinds', ' paul@pfdubois.com (Paul F. Dubois)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(243, ' Module Repository Upload Mechanism', ' jafo-pep@tummy.com (Sean Reifschneider)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(244, ' The ``directive`` statement', ' martin@v.loewis.de (Martin von LÃ¶wis)', ' Standards Track', NULL, NULL, NULL, ' 2.1'),
	(245, ' Python Interface Syntax', ' Michel Pelletier &lt;michel@users.sourceforge.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(246, ' Object Adaptation', ' aleaxit@gmail.com (Alex Martelli),', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(247, ' API for Cryptographic Hash Functions', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(248, ' Python Database API Specification v1.0', ' mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Informational', NULL, NULL, NULL, NULL),
	(249, ' Python Database API Specification v2.0', ' mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Informational', NULL, NULL, NULL, NULL),
	(250, ' Using site-packages on Windows', ' p.f.moore@gmail.com (Paul Moore)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(251, ' Python 2.2 Release Schedule', ' barry@python.org (Barry Warsaw), guido@python.org (Guido van Rossum)', ' Informational', NULL, NULL, NULL, ' 2.2'),
	(252, ' Making Types Look More Like Classes', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(253, ' Subtyping Built-in Types', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(254, ' Making Classes Look More Like Types', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(255, ' Simple Generators', ' nas@arctrix.com (Neil Schemenauer),', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(256, ' Docstring Processing System Framework', ' David Goodger &lt;goodger@python.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(257, ' Docstring Conventions', ' David Goodger &lt;goodger@python.org&gt;,', ' Informational', NULL, NULL, NULL, NULL),
	(258, ' Docutils Design Specification', ' David Goodger &lt;goodger@python.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(259, ' Omit printing newline after newline', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(260, ' Simplify xrange()', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(261, ' Support for &quot;wide&quot; Unicode characters', ' Paul Prescod &lt;paul@prescod.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(262, ' A Database of Installed Python Packages', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(263, ' Defining Python Source Code Encodings', ' mal@lemburg.com (Marc-AndrÃ© Lemburg),', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(264, ' Future statements in simulated shells', ' Michael Hudson &lt;mwh@python.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(265, ' Sorting Dictionaries by Value', ' g2@iowegian.com (Grant Griffin)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(266, ' Optimizing Global Variable/Attribute Access', ' skip@pobox.com (Skip Montanaro)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(267, ' Optimized Access to Module Namespaces', ' jeremy@alum.mit.edu (Jeremy Hylton)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(268, ' Extended HTTP functionality and WebDAV', ' gstein@lyra.org (Greg Stein)', ' Standards Track', NULL, NULL, NULL, ' 2.x'),
	(269, ' Pgen Module for Python', ' jriehl@spaceship.com (Jonathan Riehl)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(270, ' uniq method for list objects', ' jp@demonseed.net (Jason Petrone)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(271, ' Prefixing sys.path by command line option', ' fred@arakne.com (FrÃ©dÃ©ric B. Giacometti)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(272, ' API for Block Encryption Algorithms v1.0', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(273, ' Import Modules from Zip Archives', ' jim@interet.com (James C. Ahlstrom)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(274, ' Dict Comprehensions', ' Barry Warsaw &lt;barry@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7, 3.0 (originally 2.3)'),
	(275, ' Switching on Multiple Values', ' mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Standards Track', NULL, NULL, NULL, ' 2.6'),
	(276, ' Simple Iterator for ints', ' james_althoff@i2.com (Jim Althoff)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(277, ' Unicode file name support for Windows NT', ' neilh@scintilla.org (Neil Hodgson)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(278, ' Universal Newline Support', ' jack@cwi.nl (Jack Jansen)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(279, ' The enumerate() built-in function', ' python@rcn.com (Raymond Hettinger)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(280, ' Optimizing access to globals', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(281, ' Loop Counter Iteration with range and xrange', ' magnus@hetland.org (Magnus Lie Hetland)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(282, ' A Logging System', ' vinay_sajip at red-dove.com (Vinay Sajip),', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(283, ' Python 2.3 Release Schedule', ' Guido van Rossum', ' Informational', NULL, NULL, NULL, ' 2.3'),
	(284, ' Integer for-loops', ' David Eppstein &lt;eppstein@ics.uci.edu&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(285, ' Adding a bool type', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(286, ' Enhanced Argument Tuples', ' martin@v.loewis.de (Martin von LÃ¶wis)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(287, ' reStructuredText Docstring Format', ' David Goodger &lt;goodger@python.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(288, ' Generators Attributes and Exceptions', ' python@rcn.com (Raymond Hettinger)', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(289, ' Generator Expressions', ' python@rcn.com (Raymond Hettinger)', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(290, ' Code Migration and Modernization', ' Raymond Hettinger &lt;python@rcn.com&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(291, ' Backward Compatibility for the Python 2 Standard Library', ' nnorwitz@gmail.com (Neal Norwitz)', ' Informational', NULL, NULL, NULL, ' 2.3'),
	(292, ' Simpler String Substitutions', ' barry@python.org (Barry Warsaw)', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(293, ' Codec Error Handling Callbacks', ' Walter DÃ¶rwald &lt;walter@livinglogic.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(294, ' Type Names in the types Module', ' oren at hishome.net (Oren Tirosh)', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(295, ' Interpretation of multiline string constants', ' yozh@mx1.ru (Stepan Koltsov)', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(296, ' Adding a bytes Object Type', ' xscottg at yahoo.com (Scott Gilbert)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(297, ' Support for System Upgrades', ' mal@lemburg.com (Marc-AndrÃ© Lemburg)', ' Standards Track', NULL, NULL, NULL, ' 2.6'),
	(298, ' The Locked Buffer Interface', ' Thomas Heller &lt;theller@python.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(299, ' Special __main__() function in modules', ' Jeff Epler &lt;jepler@unpythonic.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(301, ' Package Index and Metadata for Distutils', ' Richard Jones &lt;richard@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(302, ' New Import Hooks', ' Just van Rossum &lt;just@letterror.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(303, ' Extend divmod() for Multiple Divisors', ' Thomas Bellman &lt;bellman+pep-divmod@lysator.liu.se&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(304, ' Controlling Generation of Bytecode Files', ' Skip Montanaro', ' Standards Track', NULL, NULL, NULL, NULL),
	(305, ' CSV File API', ' Kevin Altis &lt;altis@semi-retired.com&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(306, ' How to Change Python&#39;s Grammar', ' Michael Hudson &lt;mwh@python.net&gt;, Jack Diederich &lt;jackdied@gmail.com&gt;, Nick Coghlan &lt;ncoghlan@gmail.com&gt;, Benjamin Peterson &lt;benjamin@python.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(307, ' Extensions to the pickle protocol', ' Guido van Rossum, Tim Peters', ' Standards Track', NULL, NULL, NULL, NULL),
	(308, ' Conditional Expressions', ' Guido van Rossum, Raymond Hettinger', ' Standards Track', NULL, NULL, NULL, NULL),
	(309, ' Partial Function Application', ' Peter Harris &lt;scav@blueyonder.co.uk&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(310, ' Reliable Acquisition/Release Pairs', ' Michael Hudson &lt;mwh@python.net&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(311, ' Simplified Global Interpreter Lock Acquisition for Extensions', ' Mark Hammond &lt;mhammond@skippinet.com.au&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(312, ' Simple Implicit Lambda', ' Roman Suzi &lt;rnd@onego.ru&gt;, Alex Martelli &lt;aleaxit@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(313, ' Adding Roman Numeral Literals to Python', ' Mike Meyer &lt;mwm@mired.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(314, ' Metadata for Python Software Packages v1.1', ' A.M. Kuchling, Richard Jones', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(315, ' Enhanced While Loop', ' Raymond Hettinger &lt;python@rcn.com&gt;, W Isaac Carroll &lt;icarroll@pobox.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(316, ' Programming by Contract for Python', ' Terence Way &lt;terry@wayforward.net&gt;', ' Standards Track', NULL, NULL, NULL, ''),
	(317, ' Eliminate Implicit Exception Instantiation', ' Steven Taschuk &lt;staschuk@telusplanet.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(318, ' Decorators for Functions and Methods', ' Kevin D. Smith &lt;Kevin.Smith@theMorgue.org&gt;, Jim J. Jewett, Skip Montanaro, Anthony Baxter', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(319, ' Python Synchronize/Asynchronize Block', ' Michel Pelletier &lt;michel@users.sourceforge.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4?'),
	(320, ' Python 2.4 Release Schedule', ' Barry Warsaw, Raymond Hettinger, Anthony Baxter', ' Informational', NULL, NULL, NULL, ' 2.4'),
	(321, ' Date/Time Parsing and Formatting', ' A.M. Kuchling &lt;amk@amk.ca&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(322, ' Reverse Iteration', ' Raymond Hettinger &lt;python@rcn.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(323, ' Copyable Iterators', ' Alex Martelli &lt;aleaxit@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(324, ' subprocess - New process module', ' Peter Astrand &lt;astrand@lysator.liu.se&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(325, ' Resource-Release Support for Generators', ' Samuele Pedroni &lt;pedronis@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(326, ' A Case for Top and Bottom Values', ' Josiah Carlson &lt;jcarlson@uci.edu&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(327, ' Decimal Data Type', ' Facundo Batista &lt;facundo@taniquetil.com.ar&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(328, ' Imports: Multi-Line and Absolute/Relative', ' Aahz &lt;aahz@pythoncraft.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4, 2,5, 2.6'),
	(329, ' Treating Builtins as Constants in the Standard Library', ' Raymond Hettinger &lt;python@rcn.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(330, ' Python Bytecode Verification', ' Michel Pelletier &lt;michel@users.sourceforge.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6?'),
	(331, ' Locale-Independent Float/String Conversions', ' Christian R. Reis &lt;kiko at async.com.br&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.4'),
	(332, ' Byte vectors and String/Unicode Unification', ' Skip Montanaro &lt;skip@pobox.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(333, ' Python Web Server Gateway Interface v1.0', ' Phillip J. Eby &lt;pje@telecommunity.com&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(334, ' Simple Coroutines via SuspendIteration', ' Clark C. Evans &lt;cce@clarkevans.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(335, ' Overloadable Boolean Operators', ' Gregory Ewing &lt;greg.ewing@canterbury.ac.nz&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(336, ' Make None Callable', ' Andrew McClelland &lt;eternalsquire@comcast.net&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(337, ' Logging Usage in the Standard Library', ' Michael P. Dubner &lt;dubnerm@mindless.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(338, ' Executing modules as scripts', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(339, ' Design of the CPython Compiler', ' Brett Cannon &lt;brett@python.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(340, ' Anonymous Block Statements', ' Guido van Rossum', ' Standards Track', NULL, NULL, NULL, NULL),
	(341, ' Unifying try-except and try-finally', ' Georg Brandl &lt;georg@python.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(342, ' Coroutines via Enhanced Generators', ' Guido van Rossum, Phillip J. Eby', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(343, ' The &quot;with&quot; Statement', ' Guido van Rossum, Nick Coghlan', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(344, ' Exception Chaining and Embedded Tracebacks', ' Ka-Ping Yee', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(345, ' Metadata for Python Software Packages 1.2', ' Richard Jones &lt;richard@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(346, ' User Defined (&quot;``with``&quot;) Statements', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(347, ' Migrating the Python CVS to Subversion', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Process', NULL, NULL, NULL, NULL),
	(348, ' Exception Reorganization for Python 3.0', ' Brett Cannon &lt;brett@python.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(349, ' Allow str() to return unicode strings', ' Neil Schemenauer &lt;nas@arctrix.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(350, ' Codetags', ' Micah Elliott &lt;mde at tracos.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(351, ' The freeze protocol', ' Barry Warsaw &lt;barry@python.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(352, ' Required Superclass for Exceptions', ' Brett Cannon, Guido van Rossum', ' Standards Track', NULL, NULL, NULL, NULL),
	(353, ' Using ssize_t as the index type', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(354, '          Enumerations in Python', '         Ben Finney &lt;ben+python@benfinney.id.au&gt;', '           Standards Track', NULL, NULL, NULL, ' 2.6'),
	(355, ' Path - Object oriented filesystem paths', ' BjÃ¶rn Lindqvist &lt;bjourne@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(356, ' Python 2.5 Release Schedule', ' Neal Norwitz, Guido van Rossum, Anthony Baxter', ' Informational', NULL, NULL, NULL, ' 2.5'),
	(357, ' Allowing Any Object to be Used for Slicing', ' Travis Oliphant &lt;oliphant@ee.byu.edu&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.5'),
	(358, ' The &quot;bytes&quot; Object', ' Neil Schemenauer &lt;nas@arctrix.com&gt;, Guido van Rossum &lt;guido@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6, 3.0'),
	(359, ' The &quot;make&quot; Statement', ' Steven Bethard &lt;steven.bethard@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6'),
	(360, ' Externally Maintained Packages', ' Brett Cannon &lt;brett@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(361, ' Python 2.6 and 3.0 Release Schedule', ' Neal Norwitz, Barry Warsaw', ' Informational', NULL, NULL, NULL, ' 2.6 and 3.0'),
	(362, ' Function Signature Object', ' Brett Cannon &lt;brett@python.org&gt;, Jiwon Seo &lt;seojiwon@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(363, ' Syntax For Dynamic Attribute Access', ' Ben North &lt;ben@redfrontdoor.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(364, ' Transitioning to the Py3K Standard Library', ' Barry Warsaw &lt;barry@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6'),
	(365, ' Adding the pkg_resources module', ' Phillip J. Eby &lt;pje@telecommunity.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(366, ' Main module explicit relative imports', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6, 3.0'),
	(367, ' New Super', ' Calvin Spealman &lt;ironfroggy@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.6'),
	(368, ' Standard image protocol and class', ' Lino Mastrodomenico &lt;l.mastrodomenico@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6, 3.0'),
	(369, ' Post import hooks', ' Christian Heimes &lt;christian@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6, 3.0'),
	(370, ' Per user site-packages directory', ' Christian Heimes &lt;christian@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6, 3.0'),
	(371, ' Addition of the multiprocessing package to the standard library', ' Jesse Noller &lt;jnoller@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.6 / 3.0'),
	(372, ' Adding an ordered dictionary to collections', ' Armin Ronacher &lt;armin.ronacher@active-4.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7, 3.1'),
	(373, ' Python 2.7 Release Schedule', ' Benjamin Peterson &lt;benjamin@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 2.7'),
	(374, ' Choosing a distributed VCS for the Python project', ' Brett Cannon &lt;brett@python.org&gt;,', ' Process', NULL, NULL, NULL, NULL),
	(375, ' Python 3.1 Release Schedule', ' Benjamin Peterson &lt;benjamin@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.1'),
	(376, ' Database of Installed Python Distributions', ' Tarek ZiadÃ© &lt;tarek@ziade.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7, 3.2'),
	(377, ' Allow __enter__() methods to skip the statement body', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7, 3.1'),
	(378, ' Format Specifier for Thousands Separator', ' Raymond Hettinger &lt;python@rcn.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7 and 3.1'),
	(379, ' Adding an Assignment Expression', ' Jervis Whitley &lt;jervisau@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7, 3.2'),
	(380, ' Syntax for Delegating to a Subgenerator', ' Gregory Ewing &lt;greg.ewing@canterbury.ac.nz&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(381, ' Mirroring infrastructure for PyPI', ' Tarek ZiadÃ© &lt;tarek@ziade.org&gt;, Martin v. LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' N.A.'),
	(382, ' Namespace Packages', ' Martin v. LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.2'),
	(383, ' Non-decodable Bytes in System Character Interfaces', ' Martin v. LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.1'),
	(384, ' Defining a Stable ABI', ' Martin v. LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.2'),
	(385, ' Migrating from Subversion to Mercurial', ' Dirkjan Ochtman &lt;dirkjan@ochtman.nl&gt;,', ' Process', NULL, NULL, NULL, NULL),
	(386, ' Changing the version comparison module in Distutils', ' Tarek ZiadÃ© &lt;tarek@ziade.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(387, ' Backwards Compatibility Policy', ' Benjamin Peterson &lt;benjamin@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(389, ' argparse - New Command Line Parsing Module', ' Steven Bethard &lt;steven.bethard@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7 and 3.2'),
	(390, ' Static metadata for Distutils', ' Tarek ZiadÃ© &lt;tarek@ziade.org&gt;', ' Standards Track', ' Nick Coghlan', NULL, NULL, ' 2.7 and 3.2'),
	(391, ' Dictionary-Based Configuration For Logging', ' Vinay Sajip &lt;vinay_sajip at red-dove.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.7, 3.2'),
	(392, ' Python 3.2 Release Schedule', ' Georg Brandl &lt;georg@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.2'),
	(393, ' Flexible String Representation', ' Martin v. LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(394, ' The &quot;python&quot; Command on Unix-Like Systems', ' Kerrick Staley &lt;mail@kerrickstaley.com&gt;,', ' Informational', NULL, NULL, NULL, NULL),
	(395, ' Qualified Names for Modules', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(396, ' Module Version Numbers', ' Barry Warsaw &lt;barry@python.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(397, ' Python launcher for Windows', ' Mark Hammond &lt;mhammond@skippinet.com.au&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(398, ' Python 3.3 Release Schedule', ' Georg Brandl &lt;georg@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.3'),
	(399, ' Pure Python/C Accelerator Module Compatibility Requirements', ' Brett Cannon &lt;brett@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.3'),
	(400, ' Deprecate codecs.StreamReader and codecs.StreamWriter', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(401, ' BDFL Retirement', ' Barry Warsaw, Brett Cannon', ' Process', NULL, NULL, NULL, NULL),
	(402, ' Simplified Package Layout and Partitioning', ' P.J. Eby', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(403, ' General purpose decorator clause (aka &quot;@in&quot; clause)', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(404, ' Python 2.8 Un-release Schedule', ' Barry Warsaw &lt;barry@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 2.8'),
	(405, ' Python Virtual Environments', ' Carl Meyer &lt;carl@oddbird.net&gt;', ' Standards Track', ' Nick Coghlan', NULL, NULL, ' 3.3'),
	(406, ' Improved Encapsulation of Import State', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;, Greg Slodkowicz &lt;jergosh@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(407, ' New release cycle and introducing long-term support versions', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;,', ' Process', NULL, NULL, NULL, NULL),
	(408, ' Standard library __preview__ package', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(409, ' Suppressing exception context', ' Ethan Furman &lt;ethan@stoneleaf.us&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(410, ' Use decimal.Decimal type for timestamps', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(411, ' Provisional packages in the Python standard library', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Informational', NULL, NULL, NULL, ' 3.3'),
	(412, ' Key-Sharing Dictionary', ' Mark Shannon &lt;mark@hotpy.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3 or 3.4'),
	(413, ' Faster evolution of the Python Standard Library', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Process', NULL, NULL, NULL, NULL),
	(414, ' Explicit Unicode Literal for Python 3.3', ' Armin Ronacher &lt;armin.ronacher@active-4.com&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(415, ' Implement context suppression with exception attributes', ' Benjamin Peterson &lt;benjamin@python.org&gt;', ' Standards Track', ' Nick Coghlan', NULL, NULL, ' 3.3'),
	(416, ' Add a frozendict builtin type', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(417, ' Including mock in the Standard Library', ' Michael Foord &lt;michael@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(418, ' Add monotonic time, performance counter, and process time functions', ' Cameron Simpson &lt;cs@zip.com.au&gt;, Jim Jewett &lt;jimjjewett@gmail.com&gt;, Stephen J. Turnbull &lt;stephen@xemacs.org&gt;, Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(419, ' Protecting cleanup statements from interruptions', ' Paul Colomiets &lt;paul@colomiets.name&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(420, ' Implicit Namespace Packages', ' Eric V. Smith &lt;eric@trueblade.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(421, ' Adding sys.implementation', ' Eric Snow &lt;ericsnowcurrently@gmail.com&gt;', ' Standards Track', ' Barry Warsaw', NULL, NULL, NULL),
	(422, ' Simpler customisation of class creation', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(423, ' Naming conventions and recipes related to packaging', ' Benoit Bryon &lt;benoit@marmelune.net&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(424, ' A method for exposing a length hint', ' Alex Gaynor &lt;alex.gaynor@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(425, ' Compatibility Tags for Built Distributions', ' Daniel Holth &lt;dholth@gmail.com&gt;', ' Standards Track', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, ' 3.4'),
	(426, ' Metadata for Python Software Packages 2.0', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Standards Track', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(427, ' The Wheel Binary Package Format 1.0', ' Daniel Holth &lt;dholth@gmail.com&gt;', ' Standards Track', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(428, ' The pathlib module -- object-oriented filesystem paths', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(429, ' Python 3.4 Release Schedule', ' Larry Hastings &lt;larry@hastings.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.4'),
	(430, ' Migrating to Python 3 as the default online documentation', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Informational', ' Georg Brandl', NULL, NULL, NULL),
	(431, ' Time zone support improvements', ' Lennart Regebro &lt;regebro@gmail.com&gt;', ' Standards Track', ' Barry Warsaw &lt;barry@python.org&gt;', NULL, NULL, NULL),
	(432, ' Restructuring the CPython startup sequence', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.8'),
	(433, ' Easier suppression of file descriptor inheritance', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(434, ' IDLE Enhancement Exception for All Branches', ' Todd Rovito &lt;rovitotv@gmail.com&gt;,', ' Informational', ' Nick Coghlan', NULL, NULL, NULL),
	(435, ' Adding an Enum type to the Python standard library', ' Barry Warsaw &lt;barry@python.org&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(436, ' The Argument Clinic DSL', ' Larry Hastings &lt;larry@hastings.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(437, ' A DSL for specifying signatures, annotations and argument converters', ' Stefan Krah &lt;skrah@bytereef.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(438, ' Transitioning to release-file hosting on PyPI', ' Holger Krekel &lt;holger@merlinux.eu&gt;, Carl Meyer &lt;carl@oddbird.net&gt;', ' Process', ' Richard Jones &lt;richard@python.org&gt;', NULL, NULL, NULL),
	(439, ' Inclusion of implicit pip bootstrap in Python installation', ' Richard Jones &lt;richard@python.org&gt;', ' Standards Track', '  Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, ' 3.4'),
	(440, ' Version Identification and Dependency Specification', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Informational', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(441, ' Improving Python ZIP Application Support', ' Daniel Holth &lt;dholth@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(442, ' Safe object finalization', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', ' Benjamin Peterson &lt;benjamin@python.org&gt;', NULL, NULL, ' 3.4'),
	(443, ' Single-dispatch generic functions', ' Åukasz Langa &lt;lukasz@langa.pl&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(444, ' Python Web3 Interface', ' Chris McDonough &lt;chrism@plope.com&gt;,', ' Informational', NULL, NULL, NULL, NULL),
	(445, ' Add new APIs to customize Python memory allocators', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', NULL, NULL, ' 3.4'),
	(446, ' Make newly created file descriptors non-inheritable', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(447, ' Add __getdescriptor__ method to metaclass', ' Ronald Oussoren &lt;ronaldoussoren@mac.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(448, ' Additional Unpacking Generalizations', ' Joshua Landau &lt;joshua@landau.ws&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(449, ' Removal of the PyPI Mirror Auto Discovery and Naming Scheme', ' Donald Stufft &lt;donald@stufft.io&gt;', ' Process', ' Richard Jones &lt;richard@python.org&gt;', NULL, NULL, NULL),
	(450, ' Adding A Statistics Module To The Standard Library', ' Steven D&#39;Aprano &lt;steve@pearwood.info&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(451, ' A ModuleSpec Type for the Import System', ' Eric Snow &lt;ericsnowcurrently@gmail.com&gt;', ' Standards Track', ' Brett Cannon &lt;brett@python.org&gt;, Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, ' 3.4'),
	(452, ' API for Cryptographic Hash Functions v2.0', ' A.M. Kuchling &lt;amk@amk.ca&gt;, Christian Heimes &lt;christian@python.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(453, ' Explicit bootstrapping of pip in Python installations', ' Donald Stufft &lt;donald@stufft.io&gt;,', ' Standards Track', ' Martin von LÃ¶wis', NULL, NULL, NULL),
	(454, ' Add a new tracemalloc module to trace Python memory allocations', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', ' Charles-FranÃ§ois Natali &lt;cf.natali@gmail.com&gt;', NULL, NULL, ' 3.4'),
	(455, ' Adding a key-transforming dictionary to collections', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', ' Raymond Hettinger', NULL, NULL, ' 3.5'),
	(456, ' Secure and interchangeable hash algorithm', ' Christian Heimes &lt;christian@python.org&gt;', ' Standards Track', ' Nick Coghlan', NULL, NULL, ' 3.4'),
	(457, ' Syntax For Positional-Only Parameters', ' Larry Hastings &lt;larry@hastings.org&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(458, ' Surviving a Compromise of PyPI', ' Trishank Karthik Kuppusamy &lt;trishank@nyu.edu&gt;,', ' Standards Track', ' Richard Jones &lt;r1chardj0n3s@gmail.com&gt;', NULL, NULL, NULL),
	(459, ' Standard Metadata Extensions for Python Software Packages', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(460, ' Add binary interpolation and formatting', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(461, ' Adding % formatting to bytes and bytearray', ' Ethan Furman &lt;ethan@stoneleaf.us&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(462, ' Core development workflow automation for CPython', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Process', NULL, NULL, NULL, NULL),
	(463, ' Exception-catching expressions', ' Chris Angelico &lt;rosuav@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(464, ' Removal of the PyPI Mirror Authenticity API', ' Donald Stufft &lt;donald@stufft.io&gt;', ' Process', ' Richard Jones &lt;richard@python.org&gt;', NULL, NULL, NULL),
	(465, ' A dedicated infix operator for matrix multiplication', ' Nathaniel J. Smith &lt;njs@pobox.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(466, ' Network Security Enhancements for Python 2.7.x', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 2.7.9'),
	(467, ' Minor API improvements for binary sequences', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(468, ' Preserving the order of \\*\\*kwargs in a function.', ' Eric Snow &lt;ericsnowcurrently@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(469, ' Migration of dict iteration code to Python 3', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(470, ' Removing External Hosting Support on PyPI', ' Donald Stufft &lt;donald@stufft.io&gt;', ' Process', ' Paul Moore &lt;p.f.moore@gmail.com&gt;', NULL, NULL, NULL),
	(471, ' os.scandir() function -- a better and faster directory iterator', ' Ben Hoyt &lt;benhoyt@gmail.com&gt;', ' Standards Track', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', NULL, NULL, ' 3.5'),
	(472, ' Support for indexing with keyword arguments', ' Stefano Borini, Joseph Martinot-Lagarde ', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(473, ' Adding structured data to built-in exceptions', ' Sebastian Kreft &lt;skreft@deezer.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(474, ' Creating forge.python.org', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Process', NULL, NULL, NULL, NULL),
	(475, ' Retry system calls failing with EINTR', ' Charles-FranÃ§ois Natali &lt;cf.natali@gmail.com&gt;, Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', NULL, NULL, ' 3.5'),
	(476, ' Enabling certificate verification by default for stdlib http clients', ' Alex Gaynor &lt;alex.gaynor@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(477, ' Backport ensurepip (PEP 453) to Python 2.7', ' Donald Stufft &lt;donald@stufft.io&gt;', ' Standards Track', ' Benjamin Peterson &lt;benjamin@python.org&gt;', NULL, NULL, NULL),
	(478, ' Python 3.5 Release Schedule', ' Larry Hastings &lt;larry@hastings.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.5'),
	(479, ' Change StopIteration handling inside generators', ' Chris Angelico &lt;rosuav@gmail.com&gt;, Guido van Rossum &lt;guido@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(480, ' Surviving a Compromise of PyPI: The Maximum Security Model', ' Trishank Karthik Kuppusamy &lt;trishank@nyu.edu&gt;,', ' Standards Track', ' Richard Jones &lt;r1chardj0n3s@gmail.com&gt;', NULL, NULL, NULL),
	(481, ' Migrate CPython to Git, Github, and Phabricator', ' Donald Stufft &lt;donald@stufft.io&gt;', ' Process', NULL, NULL, NULL, NULL),
	(482, ' Literature Overview for Type Hints', ' Åukasz Langa &lt;lukasz@langa.pl&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(483, ' The Theory of Type Hints', ' Guido van Rossum &lt;guido@python.org&gt;, Ivan Levkivskyi &lt;levkivskyi@gmail.com&gt;', ' Informational', NULL, NULL, NULL, NULL),
	(484, ' Type Hints', ' Guido van Rossum &lt;guido@python.org&gt;, Jukka Lehtosalo &lt;jukka.lehtosalo@iki.fi&gt;, Åukasz Langa &lt;lukasz@langa.pl&gt;', ' Standards Track', ' Mark Shannon', NULL, NULL, ' 3.5'),
	(485, ' A Function for testing approximate equality', ' Christopher Barker &lt;Chris.Barker@noaa.gov&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(486, ' Make the Python Launcher aware of virtual environments', ' Paul Moore &lt;p.f.moore@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(488, ' Elimination of PYO files', ' Brett Cannon &lt;brett@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(489, ' Multi-phase extension module initialization', ' Petr Viktorin &lt;encukou@gmail.com&gt;,', ' Standards Track', ' Eric Snow &lt;ericsnowcurrently@gmail.com&gt;', NULL, NULL, ' 3.5'),
	(490, ' Chain exceptions at C level', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(491, ' The Wheel Binary Package Format 1.9', ' Daniel Holth &lt;dholth@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(492, ' Coroutines with async and await syntax', ' Yury Selivanov &lt;yury@magic.io&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.5'),
	(493, ' HTTPS verification migration tools for Python 2.7', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Standards Track', ' Barry Warsaw', NULL, NULL, ' 2.7.12'),
	(494, ' Python 3.6 Release Schedule', ' Ned Deily &lt;nad@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.6'),
	(495, ' Local Time Disambiguation', ' Alexander Belopolsky &lt;alexander.belopolsky@gmail.com&gt;, Tim Peters &lt;tim.peters@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(496, ' Environment Markers', ' James Polley &lt;jp@jamezpolley.com&gt;', ' Informational', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(497, ' A standard mechanism for backward compatibility', '	Ed Schofield &lt;ed at pythoncharmers.com&gt;', ' Process', NULL, NULL, NULL, NULL),
	(498, ' Literal String Interpolation', ' Eric V. Smith &lt;eric@trueblade.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(499, ' ``python -m foo`` should bind ``sys.modules[&#39;foo&#39;]`` in addition to ``sys.modules[&#39;__main__&#39;]``', ' Cameron Simpson &lt;cs@zip.com.au&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(500, ' A protocol for delegating datetime methods to their', ' Alexander Belopolsky &lt;alexander.belopolsky@gmail.com&gt;, Tim Peters &lt;tim.peters@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(501, ' General purpose string interpolation', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(502, ' String Interpolation - Extended Discussion', ' Mike G. Miller', ' Informational', NULL, NULL, NULL, ' 3.6'),
	(503, ' Simple Repository API', ' Donald Stufft &lt;donald@stufft.io&gt;', ' Informational', ' Donald Stufft &lt;donald@stufft.io&gt;', NULL, NULL, NULL),
	(504, ' Using the System RNG by default', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(505, ' None-aware operators', ' Mark E. Haase &lt;mehaase@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(506, ' Adding A Secrets Module To The Standard Library', ' Steven D&#39;Aprano &lt;steve@pearwood.info&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(507, ' Migrate CPython to Git and GitLab', ' Barry Warsaw &lt;barry@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(508, ' Dependency specification for Python Software Packages', ' Robert Collins &lt;rbtcollins@hp.com&gt;', ' Standards Track', ' Donald Stufft &lt;donald@stufft.io&gt;', NULL, NULL, NULL),
	(509, ' Add a private version to dict', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(510, ' Specialize functions with guards', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(511, ' API for code transformers', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(512, ' Migrating from hg.python.org to GitHub', ' Brett Cannon &lt;brett@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(513, ' A Platform Tag for Portable Linux Built Distributions', ' Robert T. McGibbon &lt;rmcgibbo@gmail.com&gt;, Nathaniel J. Smith &lt;njs@pobox.com&gt;', ' Informational', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(514, ' Python registration in the Windows registry', ' Steve Dower &lt;steve.dower@python.org&gt;', ' Informational', ' Paul Moore &lt;p.f.moore@gmail.com&gt;', NULL, NULL, NULL),
	(515, ' Underscores in Numeric Literals', ' Georg Brandl, Serhiy Storchaka', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(516, ' Build system abstraction for pip/conda etc', ' Robert Collins &lt;rbtcollins@hp.com&gt;,', ' Standards Track', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(517, ' A build-system independent format for source trees', ' Nathaniel J. Smith &lt;njs@pobox.com&gt;,', ' Standards Track', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', NULL, NULL, NULL),
	(518, ' Specifying Minimum Build System Requirements for Python Projects', ' Brett Cannon &lt;brett@python.org&gt;,', ' Informational', ' Nick Coghlan', NULL, NULL, NULL),
	(520, ' Preserving Class Attribute Definition Order', ' Eric Snow &lt;ericsnowcurrently@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(521, ' Managing global context via &#39;with&#39; blocks in generators and coroutines', ' Nathaniel J. Smith &lt;njs@pobox.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(522, ' Allow BlockingIOError in security sensitive APIs', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;, Nathaniel J. Smith &lt;njs@pobox.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(523, ' Adding a frame evaluation API to CPython', ' Brett Cannon &lt;brett@python.org&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(524, ' Make os.urandom() blocking on Linux', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(525, ' Asynchronous Generators', ' Yury Selivanov &lt;yury@magic.io&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(530, ' Asynchronous Comprehensions', ' Yury Selivanov &lt;yury@magic.io&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(531, ' Existence checking operators', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(532, ' A circuit breaking protocol and binary operators', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(533, ' Deterministic cleanup for iterators', ' Nathaniel J. Smith', ' Standards Track', NULL, NULL, NULL, NULL),
	(534, ' Distributing a Subset of the Standard Library', ' TomÃ¡Å¡ Orsava &lt;tomas.n@orsava.cz&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(535, ' Rich comparison chaining', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(536, ' Final Grammar for Literal String Interpolation', ' Philipp Angerer &lt;phil.angerer@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(537, ' Python 3.7 Release Schedule', ' Ned Deily &lt;nad@python.org&gt;', ' Informational', NULL, NULL, NULL, ' 3.7'),
	(538, ' Coercing the legacy C locale to C.UTF-8', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(539, ' A New C-API for Thread-Local Storage in CPython', ' Erik M. Bray, Masayuki Yamamoto', ' Informational', ' Nick Coghlan', NULL, NULL, NULL),
	(540, ' Add a new UTF-8 mode', ' Victor Stinner &lt;victor.stinner@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.7'),
	(541, ' Package Index Name Retention', ' Åukasz Langa &lt;lukasz@langa.pl&gt;', ' Process', ' Donald Stufft &lt;donald@stufft.io&gt;', NULL, NULL, NULL),
	(542, ' Dot Notation Assignment In Function Header', ' Markus Meskanen &lt;markusmeskanen@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(628, ' Add ``math.tau``', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.6'),
	(666, ' Reject Foolish Indentation', ' lac@strakt.com (Laura Creighton)', ' Standards Track', NULL, NULL, NULL, ' 2.2'),
	(754, ' IEEE 754 Floating Point Special Values', ' Gregory R. Warnes &lt;gregory_r_warnes@groton.pfizer.com&gt; (Pfizer, Inc.)', ' Standards Track', NULL, NULL, NULL, ' 2.3'),
	(3000, ' Python 3000', ' Guido van Rossum &lt;guido@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(3001, ' Procedure for reviewing and improving standard library modules', ' Georg Brandl &lt;georg@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(3002, ' Procedure for Backwards-Incompatible Changes', ' Steven Bethard &lt;steven.bethard@gmail.com&gt;', ' Process', NULL, NULL, NULL, NULL),
	(3003, ' Python Language Moratorium', ' Brett Cannon, Jesse Noller, Guido van Rossum', ' Process', NULL, NULL, NULL, NULL),
	(3099, ' Things that will Not Change in Python 3000', ' Georg Brandl &lt;georg@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(3100, ' Miscellaneous Python 3.0 Plans', ' Brett Cannon &lt;brett@python.org&gt;', ' Process', NULL, NULL, NULL, NULL),
	(3101, ' Advanced String Formatting', ' Talin &lt;viridia@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3102, ' Keyword-Only Arguments', ' Talin &lt;viridia@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3103, ' A Switch/Case Statement', ' guido@python.org (Guido van Rossum)', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3104, ' Access to Names in Outer Scopes', ' Ka-Ping Yee &lt;ping@zesty.ca&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3105, ' Make print a function', ' Georg Brandl &lt;georg@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3106, ' Revamping dict.keys(), .values() and .items()', ' Guido van Rossum', ' Standards Track', NULL, NULL, NULL, NULL),
	(3107, ' Function Annotations', ' Collin Winter &lt;collinwinter@google.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3108, ' Standard Library Reorganization', ' Brett Cannon &lt;brett@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3109, ' Raising Exceptions in Python 3000', ' Collin Winter &lt;collinwinter@google.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3110, ' Catching Exceptions in Python 3000', ' Collin Winter &lt;collinwinter@google.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3111, ' Simple input built-in in Python 3000', ' Andre Roberge &lt;andre.roberge at gmail.com &gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3112, ' Bytes literals in Python 3000', ' Jason Orendorff &lt;jason.orendorff@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3113, ' Removal of Tuple Parameter Unpacking', ' Brett Cannon &lt;brett@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3114, ' Renaming iterator.next() to iterator.__next__()', ' Ka-Ping Yee &lt;ping@zesty.ca&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3115, ' Metaclasses in Python 3000', ' Talin &lt;viridia@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3116, ' New I/O', ' Daniel Stutzbach &lt;daniel@stutzbachenterprises.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3117, ' Postfix type declarations', ' Georg Brandl &lt;georg@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3118, ' Revising the buffer protocol', ' Travis Oliphant &lt;oliphant@ee.byu.edu&gt;, Carl Banks &lt;pythondev@aerojockey.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3000'),
	(3119, ' Introducing Abstract Base Classes', ' Guido van Rossum &lt;guido@python.org&gt;, Talin &lt;viridia@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(3120, ' Using UTF-8 as the default source encoding', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3121, ' Extension Module Initialization and Finalization', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3122, ' Delineation of the main module', ' Brett Cannon', ' Standards Track', NULL, NULL, NULL, NULL),
	(3123, ' Making PyObject_HEAD conform to standard C', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3124, ' Overloading, Generic Functions, Interfaces, and Adaptation', ' Phillip J. Eby &lt;pje@telecommunity.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(3125, ' Remove Backslash Continuation', ' Jim J. Jewett &lt;JimJJewett@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(3126, ' Remove Implicit String Concatenation', ' Jim J. Jewett &lt;JimJJewett@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(3127, ' Integer Literal Support and Syntax', ' Patrick Maupin &lt;pmaupin@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3128, ' BList: A Faster List-like Type', ' Daniel Stutzbach &lt;daniel@stutzbachenterprises.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 2.6 and/or 3.0'),
	(3129, ' Class Decorators', ' Collin Winter &lt;collinwinter@google.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3130, ' Access to Current Module/Class/Function', ' Jim J. Jewett &lt;jimjjewett@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3131, ' Supporting Non-ASCII Identifiers', ' Martin von LÃ¶wis &lt;martin@v.loewis.de&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3132, ' Extended Iterable Unpacking', ' Georg Brandl &lt;georg@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3133, ' Introducing Roles', ' Collin Winter &lt;collinwinter@google.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3134, ' Exception Chaining and Embedded Tracebacks', ' Ka-Ping Yee', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3135, ' New Super', ' Calvin Spealman &lt;ironfroggy@gmail.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3136, ' Labeled break and continue', ' Matt Chisholm &lt;matt-python@theory.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.1'),
	(3137, ' Immutable Bytes and Mutable Buffer', ' Guido van Rossum &lt;guido@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3138, ' String representation in Python 3000', ' Atsuo Ishimoto &lt;ishimoto--at--gembook.org&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(3139, ' Cleaning out sys and the &quot;interpreter&quot; module', ' Benjamin Peterson &lt;benjamin@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3140, ' str(container) should call str(item), not repr(item)', ' Oleg Broytman &lt;phd@phdru.name&gt;,', ' Standards Track', NULL, NULL, NULL, NULL),
	(3141, ' A Type Hierarchy for Numbers', ' Jeffrey Yasskin &lt;jyasskin@google.com&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(3142, ' Add a &quot;while&quot; clause to generator expressions', ' Gerald Britton &lt;gerald.britton@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.0'),
	(3143, 'Standard daemon process library', '            Ben Finney &lt;ben+python@benfinney.id.au&gt;', '              Standards Track', NULL, NULL, NULL, '    3.x'),
	(3144, ' IP Address Manipulation Library for the Python Standard Library', ' Peter Moody &lt;pmoody@google.com&gt;', ' Standards Track', ' Nick Coghlan', NULL, NULL, ' 3.3'),
	(3145, ' Asynchronous I/O For subprocess.Popen', ' (James) Eric Pruitt, Charles R. McCreary, Josiah Carlson', ' Standards Track', NULL, NULL, NULL, ' 3.2'),
	(3146, ' Merging Unladen Swallow into CPython', ' Collin Winter &lt;collinwinter@google.com&gt;,', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(3147, ' PYC Repository Directories', ' Barry Warsaw &lt;barry@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.2'),
	(3148, '             futures - execute computations asynchronously', '            Brian Quinlan &lt;brian@sweetapp.com&gt;', '              Standards Track', NULL, NULL, NULL, '    3.2'),
	(3149, ' ABI version tagged .so files', ' Barry Warsaw &lt;barry@python.org&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.2'),
	(3150, ' Statement local namespaces (aka &quot;given&quot; clause)', ' Nick Coghlan &lt;ncoghlan@gmail.com&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(3151, ' Reworking the OS and IO exception hierarchy', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', ' Barry Warsaw', NULL, NULL, ' 3.3'),
	(3152, ' Cofunctions', ' Gregory Ewing &lt;greg.ewing@canterbury.ac.nz&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(3153, ' Asynchronous IO support', ' Laurens Van Houtven &lt;_@lvh.cc&gt;', ' Standards Track', NULL, NULL, NULL, NULL),
	(3154, ' Pickle protocol version 4', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.4'),
	(3155, ' Qualified name for classes and functions', ' Antoine Pitrou &lt;solipsis@pitrou.net&gt;', ' Standards Track', NULL, NULL, NULL, ' 3.3'),
	(3156, ' Asynchronous IO Support Rebooted: the &quot;asyncio&quot; Module', ' Guido van Rossum &lt;guido@python.org&gt;', ' Standards Track', ' Antoine Pitrou &lt;antoine@python.org&gt;', NULL, NULL, NULL),
	(3333, ' Python Web Server Gateway Interface v1.0.1', ' P.J. Eby &lt;pje@telecommunity.com&gt;', ' Informational', NULL, NULL, NULL, NULL);
/*!40000 ALTER TABLE `pepdetails` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
