CREATE TABLE IF NOT EXISTS sentiment_health_candidates (
    id INT NOT NULL AUTO_INCREMENT,
    proposal_identifier VARCHAR(100),
    proposal_number INT,
    message_id VARCHAR(255),
    thread_id VARCHAR(255),
    parent_message_id VARCHAR(255),
    author_name VARCHAR(255),
    author_email VARCHAR(255),
    author_role VARCHAR(255),
    message_date VARCHAR(100),
    sentence TEXT,
    sentiment_categories VARCHAR(500),
    primary_sentiment_category VARCHAR(100),
    sentiment_polarity VARCHAR(50),
    sentiment_target VARCHAR(100),
    health_signals VARCHAR(500),
    primary_health_signal VARCHAR(100),
    health_dimensions VARCHAR(500),
    primary_health_dimension VARCHAR(100),
    intensity_level INT,
    intensity_label VARCHAR(100),
    health_support_score DOUBLE,
    health_risk_score DOUBLE,
    overall_health_label VARCHAR(100),
    final_decision VARCHAR(100),
    decision_relationship VARCHAR(255),
    extraction_scheme VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_shm_proposal_number (proposal_number),
    INDEX idx_shm_message_id (message_id),
    INDEX idx_shm_author_email (author_email),
    INDEX idx_shm_sentiment_polarity (sentiment_polarity),
    INDEX idx_shm_health_dimension (primary_health_dimension),
    INDEX idx_shm_final_decision (final_decision)
);
